### ISSUE TITLE
Need tests for watch evaluation that result in errors

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-debug-nodejs#13]
`test-v8debugapi` exercises conditions, but doesn't do a lot of testing of watch expressions, specially ones that are going to be valid expressions but will fail to evaluate.

**Comment by matthewloring** [comment]
What if, instead of evaluating watch expressions manually, we allowed node to take care of that part with something like:
```javascript
vm.runInContext(`try { ${watch_expression} } catch (e) { e }`,
  vm.createContext(clone(global)));
```
This would give nice error handling and let the expression execute in a completely sandboxed way to prevent side affects being a problem. There is probably a performance trade off here but I'd have to test the current implementation against this to get more information.

**Comment by ofrobots** [comment]
I don't think `global` has enough state. You also need all the variables reachable from the stack.
