### ISSUE TITLE
GKE: Error scanning the filesystem

### ISSUE THREAD

**Issue by blerest** [GoogleCloudPlatform/cloud-debug-nodejs#377]
When I start the debug agent on GCP GKE I have the following error:

> ERROR:@google-cloud/debug-agent: Error scanning the filesystem. Error: ENOENT: no such file or directory, lstat '/proc/15/fd/11'

I'm not able to see the application on debug UI.

```
require('@google-cloud/debug-agent').start({
  allowExpressions: true,
  serviceContext: {
    service: 'service-sms',
  },
});
```

My cluster has the the `cloud_debugger` OAuth scope.

**Comment by ofrobots** [comment]
Thanks for the bug report. We'll take a look at this.

In the meanwhile, my theory is that you are building your docker image with the app (specifically `package.json`) being in the root directory. We try to scan the file system starting from the root directory to find all the `.js` files that could potentially see a breakpoint. In this case since your `package.json` is in the root directory, we probably ended up scanning the entire filesystem (we need to fix this).

As a work-around, can you try putting your app into a sub-directory, say `/app`? Let us know if that helps.

**Comment by blerest** [comment]
> As a work-around, can you try putting your app into a sub-directory, say /app? Let us know if that helps.

Yeah I just changed the WORKDIR and it's now working.

**Comment by DominicKramer** [comment]
This issue is being addressed by PR #379

**Comment by DominicKramer** [comment]
PR #381 implements a change where the agent won't start if the working directory is a root directory to avoid scanning the entire filesystem during startup for Javascript files.

**Comment by DominicKramer** [comment]
`@google-cloud/debug-agent` version `2.3.2` addresses this issue.
