### ISSUE TITLE
Convert from Travis to Kokoro

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/cloud-debug-nodejs#443]
This is one of the few repos we still have over on TravisCI.  We're starting to look at moving over to Kokoro, and this might be a good test case.  

I know @fhinkel has gone through this process, and @theacodes is largely pushing the effort. Is there a migration guide out there we can use?

**Comment by theacodes** [comment]
Our internal team site has guidance.

**Comment by DominicKramer** [comment]
@theacodes would you like to implement this change, and I can help you with any debug agent specific questions, or would you want me to implement this change, and you can help me with any Kokoro related questions?  I thought the former might be better since this is the first repo switching to Kokoro, but I wanted to get your feedback.

**Comment by ofrobots** [comment]
In the short term this is not happening, so I am going to close this issue out. A new issue can be opened when Kokoro is being rolled out across libraries.

If you disagree, please reopen.
