### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/cloud-debug-nodejs#446]
The test `should re-fetch breakpoints on error` was flaking, so I had to skip it.
https://travis-ci.org/GoogleCloudPlatform/cloud-debug-nodejs/builds

Lets fix the flake and get it re-enabled :)

**Comment by ofrobots** [comment]
Merging #466 into this issue. @DominicKramer had this comment over there:

> Flakiness in the unit tests were causing issues with landing PR #463. Fix the tests.

I continue to see flakiness in ~50% of the PRs.

**Comment by ofrobots** [comment]
Another flake on https://ci.appveyor.com/project/ofrobots/cloud-debug-nodejs/build/1.0.1223 for #477.

**Comment by ofrobots** [comment]
This is an important issue, but it is not a P1. This is being actively investigated by. Moving this to P2.

**Comment by soldair** [comment]
so. another problem.
the most expected problem ever. the nocks in one test are being satisfied by requests from another.

we call. debuglet.stop() but debuglet occasionally has an inflight request that hits the nocks for the next test. All of the nocks are satisfied for the test. the test passed. It just consumes a mock setup for the next test.

this could be fixed one or all of a few ways. 

have debugglet.stop return a promise. resolving when there are no active fetches queued for registration or breakpoint fetch
tests handling nocks should be refactored as so
```
scope.done()
debuglet.stop().then(done)
```
:point_up: :sparkles: 

clearing all the nocks. this seems to work though i haven't finished walking the code path in nock.
it seems to clear both interceptors and pending requests.
```
afterEach(()=>{
  nock.clearAll()
})
```
:point_up: :man_shrugging: 

unique the test url so each gets a unique nock scope and pass in api url somehow
the code uses an api url constant and there is no api exposed atm to override this config.
```
let testUrl = API+Date.now()
let scope = nock(testUrl)
```
:point_up: :fearful: 

use mockable timers.
because this uses setTimeout these tests are much longer than they should.
... eh at some point we should just tighten the class up so it doesn't depend on so much
:point_up: :running_man:

**Comment by soldair** [comment]
im going with the allow api url to be configured and its working really well.

here is a case where the net connect error comes from the first test but doesnt trigger until a few tests later.
 
```
      ✓ should resolve breakpointFetched promise when registration expires (95ms)
Some name Failed to re-register debuggee fake-project: Error: Debuglet not running
Some name Expressions and conditions are not allowed by default. Please set the allowExpressions configuration option to true. See the debug agent documentation at https://goo.gl/ShSm6r.
      ✓ should reject breakpoints with conditions when allowExpressions=false (1080ms)
Some name Expressions and conditions are not allowed by default. Please set the allowExpressions configuration option to true. See the debug agent documentation at https://goo.gl/ShSm6r.
Some name Error: Unable to clear breakpoint in v8
    at Object.setErrorStatusAndCallback (/usr/local/google/home/ryaneday/projects/cloud-debug-nodejs/src/agent/util/utils.ts:133:17)
    at InspectorDebugApi.clear (/usr/local/google/home/ryaneday/projects/cloud-debug-nodejs/src/agent/v8/inspector-debugapi.ts:135:20)
    at Debuglet.removeBreakpoint_ (/usr/local/google/home/ryaneday/projects/cloud-debug-nodejs/src/agent/debuglet.ts:788:20)
    at that.controller.updateBreakpoint (/usr/local/google/home/ryaneday/projects/cloud-debug-nodejs/src/agent/debuglet.ts:883:18)
    at request (/usr/local/google/home/ryaneday/projects/cloud-debug-nodejs/src/agent/controller.ts:159:9)
    at /usr/local/google/home/ryaneday/projects/cloud-debug-nodejs/node_modules/@google-cloud/common/src/service-object.ts:452:16
    at process._tickCallback (internal/process/next_tick.js:68:7)
Some name Failed to re-register debuggee fake-project: Error: Debuglet not running
      ✓ should reject breakpoints with expressions when allowExpressions=false (1099ms)
      ✓ should re-fetch breakpoints on error (1074ms)
      ✓ should expire stale breakpoints (1789ms)
Some name Unable to fetch breakpoints – stopping fetcher { NetConnectNotAllowedError: Nock: Not allow net connect for "clouddebugger.googleapis.com1:443/v2/controller/debuggees/bar/breakpoints?successOnTimeout=true"
    at /usr/local/google/home/ryaneday/projects/cloud-debug-nodejs/node_modules/nock/lib/intercept.js:407:21
    at Object.module.request (/usr/local/google/home/ryaneday/projects/cloud-debug-nodejs/node_modules/nock/lib/common.js:140:14)
    at Request.start (/usr/local/google/home/ryaneday/projects/cloud-debug-nodejs/node_modules/request/request.js:751:32)
    at Request.end (/usr/local/google/home/ryaneday/projects/cloud-debug-nodejs/node_modules/request/request.js:1511:10)
    at end (/usr/local/google/home/ryaneday/projects/cloud-debug-nodejs/node_modules/request/request.js:564:14)
    at Immediate.<anonymous> (/usr/local/google/home/ryaneday/projects/cloud-debug-nodejs/node_modules/request/request.js:578:7)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
  name: 'NetConnectNotAllowedError',
  code: 'ENETUNREACH',
  message:
   'Nock: Not allow net connect for "clouddebugger.googleapis.com1:443/v2/controller/debuggees/bar/breakpoints?successOnTimeout=true"' }
```

this is all because `debuglet.stop()` doesn't stop pending request just does its best to stop new ones

**Comment by ofrobots** [comment]
`Debuglet.stop()` returning a promise sounds A+ to me. `nock.clearAll()` is probably the easiest though. `Unique URL` will probably be the most reliable to guard against flakes.
