### ISSUE TITLE
How to handle one-liners

### ISSUE THREAD

**Issue by kilianc** [GoogleCloudPlatform/cloud-debug-nodejs#455]
Hi, I was wondering if there are options to unroll one-liners and inject logpoints/snapshots.

Example

```js
doSomething()
  .then(console.log)
  .catch((err) => reportError(err))
```

Is there a way to snapshot / log that `.catch`?

**Comment by kilianc** [comment]
I just found this article https://umaar.com/dev-tips/129-inline-breakpoints/ mentioning this feature in chrome. This would be soooo neat to have.

**Comment by ofrobots** [comment]
I agree! Currently this feature is blocked because the [Stackdriver Debugger API](https://cloud.google.com/debugger/api/) does not have support for breakpoints at a specific column. Our agent, and V8, do internally support column numbers, but the Debugger service ignores the column number at the moment.

We have had an internal bug against the Debugger service open to add this support. Let me figure out if there is a public issue tracker for the service. It would be great if you can open an external bug there too.

**Comment by ofrobots** [comment]
@kilianc would you mind opening an issue here: https://issuetracker.google.com/issues/new?component=187252&template=0

**Comment by kilianc** [comment]
Done

**Comment by ofrobots** [comment]
This is being tracked on https://b.corp.google.com/issues/111263008 now. Closing the issue here.
