### ISSUE TITLE
Support breakpoints for files inside node_modules

### ISSUE THREAD

**Issue by matthewloring** [GoogleCloudPlatform/cloud-debug-nodejs#57]

**Comment by matthewloring** [comment]
Without a way for the service to accept deployed source from the agent, it will not be possible to ensure that the deployed files are consistent with the source displayed in the debug UI. Closing this as obsolete for now.

**Comment by tcf909** [comment]
I don't think this is accurate. We very tightly couple our releases to dependency versions. Lockfiles are becoming much more common, and using specific version in package.json vs ranges (~^) is becoming more common as well.

Either way, if we are able to couple the dependency versions to a release, allowing the debug agent to work with node_modules will bring a ton of value in tracking down issues caused by dependencies.

For instance, I'm currently in the middle of debugging an issue that is being caused by a dependency and only when it is running in production (can't recreate it in dev, ci, or staging). I have the exact source of the deployed config (including dependencies), but have no way to troubleshoot what is going on in the node_modules to resolve the issue.

To solve this I'm having to rebuild the module entirely, add the debugging agent and redeploy (which is an AWFUL workaround).

Definitely think this should be looked at more closely.
